name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Set up PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build site
        run: pnpm build:site

      - name: Deploy site
        run: pnpm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
