name: Validate

on: push

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format:check

      - name: Test
        run: pnpm test
